# syntax=docker/dockerfile:1.7

ARG BASE_IMAGE_TAG=base

FROM alpine:edge AS builder

ARG GO_MODULE_PROXY=https://goproxy.cn,direct
ARG GO_SUMDB=sum.golang.google.cn

WORKDIR /src

ENV GOPATH=/go \
    GOTOOLCHAIN=auto \
    GOPROXY=${GO_MODULE_PROXY} \
    GOSUMDB=${GO_SUMDB}

RUN set -eux; \
    attempt=1; \
    while ! apk add --no-cache bash ca-certificates curl gcc git go jq musl-dev; do \
        if [ "${attempt}" -ge 5 ]; then \
            echo "apk failed after ${attempt} attempts" >&2; \
            exit 1; \
        fi; \
        attempt=$((attempt + 1)); \
        sleep $((attempt * 3)); \
    done

# Generated by scripts/prepare-openlist-source.sh from a clean git archive. It
# intentionally excludes the upstream worktree's runtime data and credentials.
COPY .docker/openlist-src/ ./

COPY drivers/feishu ./drivers/feishu
COPY integration/drivers_all.patch /tmp/drivers_all.patch

RUN git apply --check /tmp/drivers_all.patch \
    && git apply /tmp/drivers_all.patch \
    && gofmt -w drivers/feishu/*.go drivers/all.go

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go test ./drivers/feishu

# The preparation script supplies a verified frontend release that matches the
# selected backend ref. public/public.go embeds it in the binary.
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    test -f public/dist/index.html \
    && if grep -q '"/init_status"' server/router.go; then \
         grep -R -a -q -E '/api/public/init_status|/init_status' public/dist; \
       fi \
    && mkdir -p bin \
    && source_version="$(cat .openlist-source-version)" \
    && web_version="$(cat public/dist/VERSION 2>/dev/null || printf unknown)" \
    && go build -tags=jsoniter -ldflags="-w -s \
       -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.Version=${source_version}' \
       -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.WebVersion=${web_version}'" \
       -o bin/openlist .

FROM openlistteam/openlist-base-image:${BASE_IMAGE_TAG} AS runtime

ARG UID=1001
ARG GID=1001
ARG USER=openlist

LABEL org.opencontainers.image.title="OpenList with Feishu Drive" \
      org.opencontainers.image.description="OpenList with the user-OAuth Feishu Drive driver" \
      org.opencontainers.image.source="https://github.com/GeorgeHu6/openlist-feishu-driver" \
      org.opencontainers.image.licenses="AGPL-3.0-only"

WORKDIR /opt/openlist

RUN addgroup -g "${GID}" "${USER}" \
    && adduser -D -u "${UID}" -G "${USER}" "${USER}" \
    && mkdir -p /opt/openlist/data \
    && chown -R "${UID}:${GID}" /opt/openlist

COPY --from=builder --chmod=755 --chown=${UID}:${GID} /src/bin/openlist ./openlist
COPY --from=builder --chmod=755 --chown=${UID}:${GID} /src/entrypoint.sh /entrypoint.sh

USER ${USER}

ENV TZ=Asia/Shanghai \
    UMASK=022 \
    RUN_ARIA2=false

VOLUME ["/opt/openlist/data"]
EXPOSE 5244

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD wget -q --spider http://127.0.0.1:5244/ping || exit 1

ENTRYPOINT ["/entrypoint.sh"]
